-- Create __entityPlural__ table
CREATE TABLE IF NOT EXISTS __ENTITYPLURAL__ (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT current_timestamp
);

-- Create indexes for timestamp columns
CREATE INDEX IDX___ENTITYPLURAL___CREATED_AT ON __ENTITYPLURAL__ (CREATED_AT);
CREATE INDEX IDX___ENTITYPLURAL___UPDATED_AT ON __ENTITYPLURAL__ (UPDATED_AT);

-- Create trigger for automatic updated_at
CREATE TRIGGER UPDATE___ENTITYPLURAL___UPDATED_AT
BEFORE UPDATE ON __ENTITYPLURAL__
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
